### ISSUE TITLE
Plotting in scanpy

### ISSUE THREAD

**Issue by kaplinserm** [calico/scmmd#1]
Hello,

The Command Line Interface (output : 3 files) and/or the Interactive Python API (output : 2 numpy objects) works for me.
What's the python code and how do I plot the results just like the Figure 9 in your paper : [https://www.biorxiv.org/content/10.1101/2020.03.05.979112v1.full.pdf] ?

Best regards

**Comment by kaplinserm** [comment]
When I try to convert the numpy array to a pandas Dataframe in order to plot it with seaborn, I have an error.
Code : `df = pd.DataFrame(distances, index=["Cell_type_1", "Cell_type_2", "Cell_type_3", "Cell_type_4", "Cell_type_5"])`
Error : `ValueError: Must pass 2-d input. shape=(5, 100, 3)`

**Comment by jacobkimmel** [comment]
Hi, @kaplinserm,

`pd.DataFrame`s can only be formed from 2D `np.ndarray`.
By default, `scmmd` returns a two 3D arrays -- one for the MMDs (let's call it `X`) and one for the p-values (let's call it `P`) --  with the shape `[Groups, Iterations, (A->B, A->A, B->B)]` where the final dimension stores three separate comparisons.

`X[:, :, 0]` contains the comparisons across your binary contrast (e.g. group `A` vs group `B`).
`X[:, :, 1]` and `X[:, :, 2]` contain negative control comparisons of random samples in `A` vs other samples from `A`, and the same for `B`. These values should all be roughly `<= 0.` if everything is set up properly, and the corresponding p-values should all be `~= 1.`.

To convert the contrast comparisons to a dataframe, you can do:

```python
df = pd.DataFrame(
  distances[:, :, 0], # only the group A vs group B comparisons,
  columns=[f'iter_{i}' for i in range(distances.shape[1])],
  index=group_names,
)
```

To plot that, you probably want to do:

```python
pl_df = df.reset_index().melt(id_vars='index')

import seaborn as sns
sns.violinplot(
  data=pl_df,
  x='value',
  y='index',
)
```

Hope that helps!

**Comment by kaplinserm** [comment]
Thank you very much !
And how do you plot multiple experiments together ?

**Comment by jacobkimmel** [comment]
```python
def make_df(distances, experiment_name: str) -> pd.DataFrame:
  df = pd.DataFrame(
    distances[:, :, 0], # only the group A vs group B comparisons,
    columns=[f'iter_{i}' for i in range(distances.shape[1])],
    index=group_names,
  )
  df["experiment"] = experiment_name
  return df

exp_0 = make_df(distances_0, "0")
exp_1 = make_df(distances_1, "1")
df = pd.concat([exp_0, exp_1], axis=0)

pl_df = df.reset_index().melt(id_vars=['index', 'experiment'])
sns.violinplot(
  data=pl_df,
  x='value',
  y='index',
  hue='experiment',
)
